### ISSUE TITLE
dropDuplicateIDs() function

### ISSUE THREAD

**Issue by beckerbenj** [beckerbenj/eatGADS#67]
Could a `dropDuplicateIDs()` function be implemented, which drops rows based on duplicate IDs? Row selection should be either random or based on number of missing values on key variables.

Feature request by @enkeflor and @liebelta

**Comment by enkeflor** [comment]
@beckerbenj 
1) Dropping ID`s automatically should be based on the number of missings only. Keep ID`s with fewer missings. 
2) If the number of missings is equal, print ID-number. Those ID`s must be checked separately.
2a) Useful would be an argument like "dropEquals" to drop those ID`s but it is not essential.
(e.g. dropDuplicateIDs(gads, dropEquals = c(12345, 78403 ...))
