### ISSUE TITLE
write_spss2 produces a syntax which is not executable in SPSS

### ISSUE THREAD

**Issue by weirichs** [beckerbenj/eatGADS#72]
The following syntax produces invalid SPSS syntax:
```
dat <- readRDS("p:/Kurzzeitprojekte/Erstleseansatz/BT2021/Daten/Daten_Methodenhaeufigkeiten/LFB_allg.RDS")
eatGADS::write_spss2(GADSdat = dat, txtPath = tempfile(fileext = ".txt"))
```
@bussejoh identified that the error is caused by variables that only contain missing values (`NA`). In this case, these variables could be deleted with a warning message.

**Comment by beckerbenj** [comment]
Not sure about the exact details in the example above, but there are definetely cases in which variables containing only missing values should **not** be deleted when exporting to `.sav`. 

I would prefer checking whether a proper bug fix is possible.

**Comment by sachseka** [comment]
ok i will check this over the next few weeks and will keep you updated on the progress

**Comment by sachseka** [comment]
Code Review & pull request is sent @beckerbenj

**Comment by beckerbenj** [comment]
I guess this should be closed @sachseka?

**Comment by sachseka** [comment]
As you prefer. You reopened it because it is loosely related to the performance issue you assigned to me, but not directly. So, in my opinion, it can be closed.

**Comment by beckerbenj** [comment]
Ah, I did not realize that via mentioning it in another issue this reopens the mentioned issue. Definetely was not on purpose, so closed for good.
